### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by vikiuvb** [AuthorizeNet/sdk-java#79] opened 2016-02-01 06:33 UTC
NullPointerException is thrown in **net.authorize.reporting.Result**

**---- Stack Trace -----**

CAUSED_BY: java.lang.NullPointerException :::
--  net.authorize.reporting.Result.importRefId(Result.java:491)
--  net.authorize.reporting.Result.createResult(Result.java:58)
--  net.authorize.Merchant.postTransaction(Merchant.java:300)

This is occurring frequently after the transaction processing outage on Jan 29, 2016.

**Comment by vikiuvb** [comment] 2016-02-06 19:11
Any updates?

**Comment by brianmc** [comment] 2016-02-07 15:08
Hi @vikiuvb, Can you supply a code snippet, we'd like to know more about your issue, specifically method you're calling, prod/test environment, etc.
Thanks

**Comment by vikiuvb** [comment] 2016-02-19 07:26
Hello @brianmc, We are using the transaction details api to fetch the settled transactions. 

Here is the code snippet.

`net.authorize.reporting.Transaction transaction = merchant.
                 createReportingTransaction(net.authorize.reporting.TransactionType.GET_SETTLED_BATCH_LIST);
            ReportingDetails reportingDetails = ReportingDetails.createReportingDetails();
            reportingDetails.setBatchFirstSettlementDate(startTime);
            reportingDetails.setBatchLastSettlementDate(endTime);
            transaction.setReportingDetails(reportingDetails);
            net.authorize.reporting.Result<net.authorize.Transaction> result = (net.authorize.reporting.Result<net.authorize.Transaction>) merchant.postTransaction(transaction);`

NullPointerException is thrown on postTransaction call.

**Comment by ramittal** [comment] 2016-02-20 18:02
Thanks Viki, while we investigate the NPE that you are noticing, you may want to try the new model, with sample at : https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetSettledBatchList.java

**Comment by KarthikeyanKumar** [comment] 2017-12-05 07:30
Hello Team,

Are you able to still reproduce this issue.Can you please confirm ?.

Thanks,
Karthikeyan

**Comment by gnongsie** [comment] 2017-12-14 10:59
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.

**Closed** 2017-12-14 11:04 UTC
