### ISSUE TITLE
Deleting User Profile via Java API returns a "reccord cannot be found error" but deletion successful

### ISSUE THREAD

**Issue by martygriffin** [AuthorizeNet/sdk-java#38] opened 2015-04-29 17:28 UTC
I am trying to delete user profiles in java via the code below.

net.authorize.cim.Transaction transaction=merchant.createCIMTransaction(TransactionType.DELETE_CUSTOMER_PROFILE);

transaction.setRefId(generateRefId());

transaction.setCustomerProfileId(profileId);

Result<Transaction> result = (Result<Transaction>) merchant.postTransaction(transaction);

Every response I get it the following

deleting user with profileId =32441194
Result Code: Error<br>
E00040 - The record cannot be found.<br>

The weird thing is the user profile Id is in fact active/correct and the deletion of the account completes successfully in the sandbox, even though the response claims there is an error.

Any ideas?

**Comment by brianmc** [comment] 2015-05-20 15:02
Hi Marty, sorry for the delay in response.  Looking into this issue right now.

Brian

**Comment by brianmc** [comment] 2015-05-20 16:23
Hi Marty, Can you repro consistently?  If so I'd like to try your sandbox credentials.  Can you email developer@authorize.net and mention my name and we can connect via email to diagnose the issue.

Thanks,

Brian

**Comment by gnongsie** [comment] 2016-07-25 06:49
Hi Marty, I am trying to reproduce this error and I am also unable to find any way to reproduce this issue. Are you still facing this issue or has it been resolved?


Thanks,
Gabriel

**Comment by gnongsie** [comment] 2017-12-14 11:05
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.

**Closed** 2017-12-14 11:06 UTC
