### ISSUE TITLE
chargeCreditCard:controller.getApiResponse() returns null response

### ISSUE THREAD

**Issue by yogeshrssquarz** [AuthorizeNet/sdk-java#113] opened 2017-05-03 07:30 UTC
I'm using latest anet-sdk version for java and im integrating it in Spring MVC project,I have used code from authorize.net sample code for java but it is giving null response now,it was working fine a month ago

**Comment by KarthikeyanKumar** [comment] 2017-12-05 08:35
Hello Yogesh,

Are u able to reproduce this?.If so can you please post the code snippet that you are trying (Kindly paste the part which includes the initialization of the controller part)?.

Thanks,
Karthikeyan

**Comment by gnongsie** [comment] 2017-12-14 11:09
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.

**Closed** 2017-12-14 11:10 UTC
